### PR TITLE
Survey repo

### PR DESCRIPTION
**Pull request by TaylorNoelJordan**
Hey @flachman03 and @Nathan-Froeh, I've been chipping away at this randomize method and would love some pointers! I'm generating a random number, but it seems to only be grabbing an integer rather than an item from the surveys array.  When I console log the random number, it pulls a new digit 5 times, so that seems weird. If I add dot notation to try to grab the ID, it returns undefined. Would love some feedback!

### CODE REVIEW

**Comment by TaylorNoelJordan** [comment]
Okay, so Nathan and I got the random method working, and now I believe this should be storing the current question and corresponding answers to be able to pass into the Round class. Let me know your thoughts!

**Comment by Nathan-Froeh** [comment]
And all your tests pass right now too? As long as that works then it all looks good to me, Ryan have you looked at this yet?

**Comment by TaylorNoelJordan** [comment]
@robbiejaeger and @thatpamiam, I also wanted to see if you had any advice on how to test for a randomized question/answer set? I have a method that randomizes the array and returns a question, and then a follow up method that returns the corresponding answers based on id. I just wasn't sure how I should build the test when the question/answers are different every time. Let me know if you could nudge me in the right direction.

**Comment by thatPamIAm** [comment]
@TaylorNoelJordan I left some notes in the other PR - but you don't need to write tests that are attempting to test for randomness.

**Pull request merged**
